name: Code Formatter
on:
   workflow_dispatch:
   push:

jobs:
   format:
      name: Code Formatting
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Cache Bun dependencies
           uses: actions/cache@v4
           with:
              path: ~/.bun/install/cache
              key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/package.json', '**/bun.lockb') }}

         - name: Setup Bun
           uses: oven-sh/setup-bun@v2
           with:
              bun-version-file: "package.json"

         - name: Install Dependencies
           run: bun install

         - name: Run ESLint
           run: bun run lint

         - name: Run Prettier
           run: bun run prettier

         - name: Automatically Commit Changed
           uses: stefanzweifel/git-auto-commit-action@v5
           with:
              push_options: "--force"
              commit_options: "--no-verify"
              commit_message: "chore: code formatting"
              skip_checkout: true
