name: Publish
on:
   workflow_dispatch:

jobs:
   format:
      name: Publish
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
           with:
              ref: ${{ github.ref }}

         - name: Cache Bun dependencies
           uses: actions/cache@v4
           with:
              path: ~/.bun/install/cache
              key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/package.json', '**/bun.lockb') }}

         - name: Write Environment Variables to .env
           run: |
              echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
              echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
              echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env

         - name: Setup Bun
           uses: oven-sh/setup-bun@v2
           with:
              bun-version-file: "package.json"

         - name: Cache turbo
           uses: actions/cache@v4
           with:
              path: .turbo
              key: ${{ runner.os }}-turbo-${{ github.sha }}
              restore-keys: |
                 ${{ runner.os }}-turbo-

         - name: Install Dependencies
           run: bun install

         - name: Run Build
           run: bun run build

         - name: Deploy to Vercel
           uses: amondnet/vercel-action@v25
           with:
              vercel-token: ${{ secrets.VERCEL_TOKEN }}
              vercel-args: "--prod --logs"
              vercel-org-id: ${{ secrets.ORG_ID }}
              vercel-project-id: ${{ secrets.PROJECT_ID }}
